create table public.django_migrations
(
    id      bigint generated by default as identity
        primary key,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table public.django_migrations
    owner to sample;

create table public.django_content_type
(
    id        integer generated by default as identity
        primary key,
    app_label varchar(100) not null,
    model     varchar(100) not null,
    constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model)
);

alter table public.django_content_type
    owner to sample;

create table public.auth_permission
(
    id              integer generated by default as identity
        primary key,
    name            varchar(255) not null,
    content_type_id integer      not null
        constraint auth_permission_content_type_id_2f476e4b_fk_django_co
            references public.django_content_type
            deferrable initially deferred,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename)
);

alter table public.auth_permission
    owner to sample;

create index auth_permission_content_type_id_2f476e4b
    on public.auth_permission (content_type_id);

create table public.auth_group
(
    id   integer generated by default as identity
        primary key,
    name varchar(150) not null
        unique
);

alter table public.auth_group
    owner to sample;

create index auth_group_name_a6ea08ec_like
    on public.auth_group (name varchar_pattern_ops);

create table public.auth_group_permissions
(
    id            bigint generated by default as identity
        primary key,
    group_id      integer not null
        constraint auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
            references public.auth_group
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
            references public.auth_permission
            deferrable initially deferred,
    constraint auth_group_permissions_group_id_permission_id_0cd325b0_uniq
        unique (group_id, permission_id)
);

alter table public.auth_group_permissions
    owner to sample;

create index auth_group_permissions_group_id_b120cbf9
    on public.auth_group_permissions (group_id);

create index auth_group_permissions_permission_id_84c5c92e
    on public.auth_group_permissions (permission_id);

create table public._user
(
    id            integer generated by default as identity
        primary key,
    last_login    timestamp with time zone,
    is_superuser  boolean      not null,
    email         varchar(254) not null
        unique,
    first_name    varchar(255),
    last_name     varchar(255),
    password      varchar(255) not null,
    role          varchar(255) not null,
    is_active     boolean,
    is_staff      boolean,
    language_code varchar(255)
);

alter table public._user
    owner to sample;

create index _user_email_16d85c91_like
    on public._user (email varchar_pattern_ops);

create table public._user_groups
(
    id         bigint generated by default as identity
        primary key,
    jwtuser_id bigint  not null
        constraint _user_groups_jwtuser_id_90ae9182_fk__user_id
            references public._user
            deferrable initially deferred,
    group_id   integer not null
        constraint _user_groups_group_id_45ff9376_fk_auth_group_id
            references public.auth_group
            deferrable initially deferred,
    constraint _user_groups_jwtuser_id_group_id_0a762303_uniq
        unique (jwtuser_id, group_id)
);

alter table public._user_groups
    owner to sample;

create index _user_groups_jwtuser_id_90ae9182
    on public._user_groups (jwtuser_id);

create index _user_groups_group_id_45ff9376
    on public._user_groups (group_id);

create table public._user_user_permissions
(
    id            bigint generated by default as identity
        primary key,
    jwtuser_id    bigint  not null
        constraint _user_user_permissions_jwtuser_id_b57923f0_fk__user_id
            references public._user
            deferrable initially deferred,
    permission_id integer not null
        constraint "D_user_user_permissio_permission_id_fc324062_fk_auth_per"
            references public.auth_permission
            deferrable initially deferred,
    constraint _user_user_permissions_jwtuser_id_permission_id_e4412350_uniq
        unique (jwtuser_id, permission_id)
);

alter table public._user_user_permissions
    owner to sample;

create index _user_user_permissions_jwtuser_id_b57923f0
    on public._user_user_permissions (jwtuser_id);

create index _user_user_permissions_permission_id_fc324062
    on public._user_user_permissions (permission_id);

create table public.imputation_algorithm
(
    id          integer generated by default as identity
        primary key,
    name        varchar(50)  not null,
    description varchar(250) not null
);

alter table public.imputation_algorithm
    owner to sample;

create table public.preprocessor_type
(
    id                integer generated by default as identity
        primary key,
    name              varchar(50)  not null
        unique,
    description       varchar(255) not null,
    schema_enum_value varchar(50)  not null,
    schema            jsonb        not null
);

alter table public.preprocessor_type
    owner to sample;

create index preprocessor_type_name_9ee78278_like
    on public.preprocessor_type (name varchar_pattern_ops);

create table public.schema_validation_forms
(
    id        bigint generated by default as identity
        primary key,
    name      varchar(30) not null,
    schema    jsonb       not null,
    ui_schema jsonb       not null
);

alter table public.schema_validation_forms
    owner to sample;

create table public.train_data_file
(
    id         integer generated by default as identity
        primary key,
    name       varchar(50)              not null,
    created_at timestamp with time zone not null,
    user_id    bigint                   not null
        constraint train_data_file_user_id_4b1b9c7d_fk__user_id
            references public._user
            deferrable initially deferred,
    constraint train_data_file_name_user_id_2cd12e9d_uniq
        unique (name, user_id)
);

alter table public.train_data_file
    owner to sample;

create index train_data_file_user_id_4b1b9c7d
    on public.train_data_file (user_id);

create table public.train_data
(
    id                bigint generated by default as identity
        primary key,
    name              varchar(50)              not null,
    time_series_value jsonb                    not null,
    time_stamp_value  jsonb                    not null,
    created_at        timestamp with time zone not null,
    file_id           integer                  not null
        constraint train_data_file_id_06bd3fd3_fk_train_data_file_id
            references public.train_data_file
            deferrable initially deferred,
    user_id           integer                  not null
        constraint train_data_user_id_176170eb_fk__user_id
            references public._user
            deferrable initially deferred
);

alter table public.train_data
    owner to sample;

create index train_data_file_id_06bd3fd3
    on public.train_data (file_id);

create index train_data_user_id_176170eb
    on public.train_data (user_id);

create table public.survey
(
    id      bigint generated by default as identity
        primary key,
    result  jsonb  not null,
    user_id bigint not null
        unique
        constraint survey_user_id_0f7667c9_fk__user_id
            references public._user
            deferrable initially deferred
);

alter table public.survey
    owner to sample;

create table public.preprocessor
(
    id              integer generated by default as identity
        primary key,
    specific_config jsonb   not null,
    type_id         integer not null
        constraint preprocessor_type_id_03baa324_fk_preprocessor_type_id
            references public.preprocessor_type
            deferrable initially deferred
);

alter table public.preprocessor
    owner to sample;

create index preprocessor_type_id_03baa324
    on public.preprocessor (type_id);

create table public.django_admin_log
(
    id              integer generated by default as identity
        primary key,
    action_time     timestamp with time zone not null,
    object_id       text,
    object_repr     varchar(200)             not null,
    action_flag     smallint                 not null
        constraint django_admin_log_action_flag_check
            check (action_flag >= 0),
    change_message  text                     not null,
    content_type_id integer
        constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co
            references public.django_content_type
            deferrable initially deferred,
    user_id         bigint                   not null
        constraint django_admin_log_user_id_c564eba6_fk__user_id
            references public._user
            deferrable initially deferred
);

alter table public.django_admin_log
    owner to sample;

create index django_admin_log_content_type_id_c4bce8eb
    on public.django_admin_log (content_type_id);

create index django_admin_log_user_id_c564eba6
    on public.django_admin_log (user_id);

create table public.ml_model
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(50)              not null,
    description varchar(255)             not null,
    i18n_key    varchar(50)              not null,
    "pyName"    varchar(255)             not null,
    created_at  timestamp with time zone not null,
    forcasting  boolean                  not null
);

alter table public.ml_model
    owner to sample;

create table public.ml_configuration
(
    id                      bigint generated by default as identity
        primary key,
    name                    varchar(50)              not null,
    description             varchar(500),
    created_at              timestamp with time zone not null,
    is_running              varchar(50),
    min_length              integer,
    imputation_algorithm_id integer
        constraint ml_configuration_imputation_algorithm_39553484_fk_imputatio
            references public.imputation_algorithm
            deferrable initially deferred,
    ml_model_id             bigint                   not null
        constraint ml_configuration_ml_model_id_1c0bf112_fk_ml_model_id
            references public.ml_model
            deferrable initially deferred,
    processing_id           integer
        unique
        constraint ml_configuration_processing_id_437ac97a_fk_preprocessor_id
            references public.preprocessor
            deferrable initially deferred,
    user_id                 integer                  not null
        constraint ml_configuration_user_id_e6a56571_fk__user_id
            references public._user
            deferrable initially deferred
);

alter table public.ml_configuration
    owner to sample;

create index ml_configuration_imputation_algorithm_id_39553484
    on public.ml_configuration (imputation_algorithm_id);

create index ml_configuration_ml_model_id_1c0bf112
    on public.ml_configuration (ml_model_id);

create index ml_configuration_user_id_e6a56571
    on public.ml_configuration (user_id);

create table public.ml_solution
(
    id                  bigint generated by default as identity
        primary key,
    generator_model     text   not null,
    gap_detector_model  text,
    ml_configuration_id bigint not null
        unique
        constraint ml_solution_ml_configuration_id_0d646548_fk_ml_configuration_id
            references public.ml_configuration
            deferrable initially deferred
);

alter table public.ml_solution
    owner to sample;

create table public.ml_training_information
(
    id                bigint generated by default as identity
        primary key,
    added_to          timestamp with time zone not null,
    training_time     integer,
    iterations        integer,
    target_iterations integer,
    target_accuracy   integer,
    accuracy          double precision         not null,
    max_length        integer,
    image             text,
    prediction_length integer,
    ml_solution_id    bigint                   not null
        constraint ml_training_informat_ml_solution_id_9e664430_fk_ml_soluti
            references public.ml_solution
            deferrable initially deferred,
    reduction_factor  integer
);

alter table public.ml_training_information
    owner to sample;

create index ml_training_information_ml_solution_id_9e664430
    on public.ml_training_information (ml_solution_id);

create table public.ml_configuration_train_data
(
    id                 bigint generated by default as identity
        primary key,
    mlconfiguration_id integer not null
        constraint ml_configuration_tra_mlconfiguration_id_7faa0ee6_fk_ml_config
            references public.ml_configuration
            deferrable initially deferred,
    traindata_id       integer not null
        constraint ml_configuration_tra_traindata_id_ae4be6f3_fk_train_dat
            references public.train_data
            deferrable initially deferred,
    constraint ml_configuration_train_d_mlconfiguration_id_train_5af4e05b_uniq
        unique (mlconfiguration_id, traindata_id)
);

alter table public.ml_configuration_train_data
    owner to sample;

create index ml_configuration_train_data_mlconfiguration_id_7faa0ee6
    on public.ml_configuration_train_data (mlconfiguration_id);

create index ml_configuration_train_data_traindata_id_ae4be6f3
    on public.ml_configuration_train_data (traindata_id);

create table public.django_session
(
    session_key  varchar(40)              not null
        primary key,
    session_data text                     not null,
    expire_date  timestamp with time zone not null
);

alter table public.django_session
    owner to sample;

create index django_session_session_key_c0390e0f_like
    on public.django_session (session_key varchar_pattern_ops);

create index django_session_expire_date_a5c62663
    on public.django_session (expire_date);

create table public.token_blacklist_outstandingtoken
(
    id         bigint generated by default as identity
        primary key,
    token      text                     not null,
    created_at timestamp with time zone,
    expires_at timestamp with time zone not null,
    user_id    bigint
        constraint token_blacklist_outstandingtoken_user_id_83bc629a_fk__user_id
            references public._user
            deferrable initially deferred,
    jti        varchar(255)             not null
        constraint token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq
            unique
);

alter table public.token_blacklist_outstandingtoken
    owner to sample;

create table public.token_blacklist_blacklistedtoken
(
    id             bigint generated by default as identity
        primary key,
    blacklisted_at timestamp with time zone not null,
    token_id       bigint                   not null
        unique
        constraint token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk
            references public.token_blacklist_outstandingtoken
            deferrable initially deferred
);

alter table public.token_blacklist_blacklistedtoken
    owner to sample;

create index token_blacklist_outstandingtoken_user_id_83bc629a
    on public.token_blacklist_outstandingtoken (user_id);

create index token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like
    on public.token_blacklist_outstandingtoken (jti varchar_pattern_ops);

create table public.tsd_models
(
    id           bigint generated by default as identity
        primary key,
    name         varchar(50)              not null,
    i18n_key     varchar(30)              not null,
    description  varchar(255)             not null,
    "pyName"     varchar(50)              not null,
    display_type varchar(50)              not null,
    created_at   timestamp with time zone not null
);

alter table public.tsd_models
    owner to sample;

create table public.tsd_configuration
(
    id                      bigint generated by default as identity
        primary key,
    name                    varchar(255)             not null,
    description             varchar(500),
    created_at              timestamp with time zone not null,
    min_length              integer,
    imputation_algorithm_id integer
        constraint tsd_configuration_imputation_algorithm_5276b8b3_fk_imputatio
            references public.imputation_algorithm
            deferrable initially deferred,
    processing_id           integer
        unique
        constraint tsd_configuration_processing_id_d52770ae_fk_preprocessor_id
            references public.preprocessor
            deferrable initially deferred,
    tsd_model_id            bigint                   not null
        constraint tsd_configuration_tsd_model_id_b96804e0_fk_tsd_models_id
            references public.tsd_models
            deferrable initially deferred,
    user_id                 integer                  not null
        constraint tsd_configuration_user_id_b90e3d42_fk__user_id
            references public._user
            deferrable initially deferred
);

alter table public.tsd_configuration
    owner to sample;

create index tsd_configuration_imputation_algorithm_id_5276b8b3
    on public.tsd_configuration (imputation_algorithm_id);

create index tsd_configuration_tsd_model_id_b96804e0
    on public.tsd_configuration (tsd_model_id);

create index tsd_configuration_user_id_b90e3d42
    on public.tsd_configuration (user_id);

create table public.tsd_training_information
(
    id                   integer generated by default as identity
        primary key,
    added_to             timestamp with time zone not null,
    accuracy             double precision         not null,
    levels               integer                  not null,
    tsd_configuration_id integer                  not null
        constraint tsd_training_informa_tsd_configuration_id_6863abe8_fk_tsd_confi
            references public.tsd_configuration
            deferrable initially deferred
);

alter table public.tsd_training_information
    owner to sample;

create index tsd_training_information_tsd_configuration_id_6863abe8
    on public.tsd_training_information (tsd_configuration_id);

create table public.tsd_configuration_train_data
(
    id                   bigint generated by default as identity
        primary key,
    level_config         jsonb,
    train_data_id        bigint not null
        constraint tsd_configuration_tr_train_data_id_5f493ef4_fk_train_dat
            references public.train_data
            deferrable initially deferred,
    tsd_configuration_id bigint not null
        constraint tsd_configuration_tr_tsd_configuration_id_01af4a8f_fk_tsd_confi
            references public.tsd_configuration
            deferrable initially deferred
);

alter table public.tsd_configuration_train_data
    owner to sample;

create index tsd_configuration_train_data_train_data_id_5f493ef4
    on public.tsd_configuration_train_data (train_data_id);

create index tsd_configuration_train_data_tsd_configuration_id_01af4a8f
    on public.tsd_configuration_train_data (tsd_configuration_id);

create table public.json_schemas
(
    id          bigint not null
        primary key,
    schema      jsonb,
    schema_type smallint
        constraint json_schemas_schema_type_check
            check ((schema_type >= 0) AND (schema_type <= 5)),
    ui_schema   jsonb
);

alter table public.json_schemas
    owner to sample;

create table public.data_type
(
    data_type_name  varchar(255) not null
        primary key,
    description     varchar(255),
    preview_showing boolean,
    data_type       smallint
        constraint data_type_data_type_check
            check ((data_type >= 0) AND (data_type <= 6)),
    schema_id       bigint
        constraint fk5wbsreubr1nicg9balslhwa85
            references public.json_schemas
);

alter table public.data_type
    owner to sample;

create table public.log_messages
(
    log_id        bigint not null
        primary key,
    data_set_name varchar(255),
    message       varchar(255),
    send_session  varchar(255),
    time_stamp    timestamp(6) with time zone,
    track_id      bigint not null
);

alter table public.log_messages
    owner to sample;

create table public.ml_config_data
(
    id                  bigint   not null
        primary key,
    generation_option   smallint not null
        constraint ml_config_data_generation_option_check
            check ((generation_option >= 0) AND (generation_option <= 1)),
    prediction_length   integer,
    starting_point      integer,
    ml_configuration_id bigint
        constraint fkl3mvjgv6wcx1w9yrinigsnly2
            references public.ml_configuration
);

alter table public.ml_config_data
    owner to sample;

create table public.projects
(
    id      bigint not null
        primary key,
    name    varchar(255),
    user_id integer
        constraint fkgc1x3kkp29h3y4rqhnyx00g2l
            references public._user
);

alter table public.projects
    owner to sample;

create table public.refresh_token
(
    id          serial
        primary key,
    expiry_date timestamp(6) with time zone,
    token       varchar(255),
    user_id     integer
        constraint uk_f95ixxe7pa48ryn1awmh2evt7
            unique
        constraint fkbws85up72jgwebb6ttkjiytg3
            references public._user
);

alter table public.refresh_token
    owner to sample;

create table public.tracks
(
    id        bigint not null
        primary key,
    name      varchar(255),
    repeating boolean,
    unit      varchar(255)
);

alter table public.tracks
    owner to sample;

create table public.projects_tracks
(
    project_id bigint not null
        constraint fksxj92wca9epx692i8l14uo1pq
            references public.projects,
    tracks_id  bigint not null
        constraint uk_q2iif7an4mdj2oo6s7tf9ml69
            unique
        constraint fkip4su624ox0tq6pq3noc6th29
            references public.tracks,
    primary key (project_id, tracks_id)
);

alter table public.projects_tracks
    owner to sample;

create table public.tracks_allowed_data_types
(
    track_id                          bigint       not null
        constraint fkfkp89ti7s8ux0paxbmxksafsk
            references public.tracks,
    allowed_data_types_data_type_name varchar(255) not null
        constraint fkicbfnxqnxb753in4fxihkk4fw
            references public.data_type,
    primary key (track_id, allowed_data_types_data_type_name)
);

alter table public.tracks_allowed_data_types
    owner to sample;

create table public.tsd_options
(
    id       bigserial
        primary key,
    residual varchar(255),
    season   varchar(255),
    trend    varchar(255)
);

alter table public.tsd_options
    owner to sample;

create table public.tsdconfig_data
(
    id         bigserial
        primary key,
    tsd_config bigint not null
        constraint fka8w5d3gjp1977281ktdl7l77x
            references public.tsd_configuration
);

alter table public.tsdconfig_data
    owner to sample;

create table public.plain_data
(
    dtype              varchar(31) not null,
    id                 bigint      not null
        primary key,
    data_type          smallint
        constraint plain_data_data_type_check
            check ((data_type >= 0) AND (data_type <= 6)),
    frequency          real,
    name               varchar(255),
    num_samples        integer,
    position           integer,
    calculation_method varchar(255)
        constraint plain_data_calculation_method_check
            check ((calculation_method)::text = ANY
                   ((ARRAY ['ADDITIVE'::character varying, 'MULTIPLICATIVE'::character varying])::text[])),
    sleep_time         integer,
    train_data_id      bigint
        constraint fkj5ysbuf61xy09hhwejoqqycuc
            references public.train_data,
    tsd_option_id      bigint
        constraint uk_pw506kyfw5xhfcf1cqj5ev1b6
            unique
        constraint fkocuvikk3u0538j8w97qnvtw8s
            references public.tsd_options,
    ml_config_id       bigint
        constraint uk_c58b2ryxxiibd6x15a30wgyx
            unique
        constraint fkjatdxcf4lmxup4cxd4v2av6js
            references public.ml_config_data,
    tsd_config_id      bigint
        constraint uk_rx3emt97nv1f3c2l927jbhujw
            unique
        constraint fkh8743fn33x7hnefo1pil3257b
            references public.tsdconfig_data
);

alter table public.plain_data
    owner to sample;

create table public.alphabet
(
    data_set_id bigint     not null
        constraint fki2ri2u5c72hihuxgpdfwfqtup
            references public.plain_data,
    character   varchar(1) not null
);

alter table public.alphabet
    owner to sample;

create table public.data_set_custom_values
(
    data_set_id   bigint  not null
        constraint fk7x3byiamwvb3xb5n84pbalfu1
            references public.plain_data,
    custom_value  double precision,
    sample_number integer not null,
    primary key (data_set_id, sample_number)
);

alter table public.data_set_custom_values
    owner to sample;

create table public.tracks_data_sets
(
    track_id     bigint not null
        constraint fkk7uvwc9r9oiwirve9ymkqc2sm
            references public.tracks,
    data_sets_id bigint not null
        constraint uk_65kdrh0pdi7rkopu5qmh67p98
            unique
        constraint fkr7hio6tckformeydohj7xhsoi
            references public.plain_data,
    primary key (track_id, data_sets_id)
);

alter table public.tracks_data_sets
    owner to sample;

create table public.tsd_level_train_data
(
    id            bigserial
        primary key,
    level_config  jsonb,
    train_data_id bigint
        constraint fkdfat8ri46e5yn7bywl3t1prwg
            references public.train_data
);

alter table public.tsd_level_train_data
    owner to sample;

create table public.tsdconfig_data_train_data
(
    tsdconfig_data_id bigint not null
        constraint fki69m6g90k6setb7p7vvelig9m
            references public.tsdconfig_data,
    train_data_id     bigint not null
        constraint uk_pkvvf872g3pkp17f2gf7r6b5k
            unique
        constraint fkgdmcn0yvgev431uutsfar7u05
            references public.tsd_level_train_data
);

alter table public.tsdconfig_data_train_data
    owner to sample;
