create database postgres
    with owner sample;

comment on database postgres is 'default administrative connection database';

create sequence public.json_schemas_seq
    increment by 50;

alter sequence public.json_schemas_seq owner to sample;

create sequence public.log_messages_seq
    increment by 50;

alter sequence public.log_messages_seq owner to sample;

create sequence public.ml_config_data_seq
    increment by 50;

alter sequence public.ml_config_data_seq owner to sample;

create sequence public.plain_data_seq
    increment by 50;

alter sequence public.plain_data_seq owner to sample;

create sequence public.projects_seq
    increment by 50;

alter sequence public.projects_seq owner to sample;

create sequence public.tracks_seq
    increment by 50;

alter sequence public.tracks_seq owner to sample;

create table public.django_migrations
(
    id      bigint generated by default as identity
        primary key,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table public.django_migrations
    owner to sample;

create table public.django_content_type
(
    id        integer generated by default as identity
        primary key,
    app_label varchar(100) not null,
    model     varchar(100) not null,
    constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model)
);

alter table public.django_content_type
    owner to sample;

create table public.auth_permission
(
    id              integer generated by default as identity
        primary key,
    name            varchar(255) not null,
    content_type_id integer      not null
        constraint auth_permission_content_type_id_2f476e4b_fk_django_co
            references public.django_content_type
            deferrable initially deferred,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename)
);

alter table public.auth_permission
    owner to sample;

create index auth_permission_content_type_id_2f476e4b
    on public.auth_permission (content_type_id);

create table public.auth_group
(
    id   integer generated by default as identity
        primary key,
    name varchar(150) not null
        unique
);

alter table public.auth_group
    owner to sample;

create index auth_group_name_a6ea08ec_like
    on public.auth_group (name varchar_pattern_ops);

create table public.auth_group_permissions
(
    id            bigint generated by default as identity
        primary key,
    group_id      integer not null
        constraint auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
            references public.auth_group
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
            references public.auth_permission
            deferrable initially deferred,
    constraint auth_group_permissions_group_id_permission_id_0cd325b0_uniq
        unique (group_id, permission_id)
);

alter table public.auth_group_permissions
    owner to sample;

create index auth_group_permissions_group_id_b120cbf9
    on public.auth_group_permissions (group_id);

create index auth_group_permissions_permission_id_84c5c92e
    on public.auth_group_permissions (permission_id);

create table public._user_groups
(
    id         bigint generated by default as identity
        primary key,
    jwtuser_id bigint  not null,
    group_id   integer not null
        constraint _user_groups_group_id_45ff9376_fk_auth_group_id
            references public.auth_group
            deferrable initially deferred,
    constraint _user_groups_jwtuser_id_group_id_0a762303_uniq
        unique (jwtuser_id, group_id)
);

alter table public._user_groups
    owner to sample;

create index _user_groups_jwtuser_id_90ae9182
    on public._user_groups (jwtuser_id);

create index _user_groups_group_id_45ff9376
    on public._user_groups (group_id);

create table public._user_user_permissions
(
    id            bigint generated by default as identity
        primary key,
    jwtuser_id    bigint  not null,
    permission_id integer not null
        constraint "D_user_user_permissio_permission_id_fc324062_fk_auth_per"
            references public.auth_permission
            deferrable initially deferred,
    constraint _user_user_permissions_jwtuser_id_permission_id_e4412350_uniq
        unique (jwtuser_id, permission_id)
);

alter table public._user_user_permissions
    owner to sample;

create index _user_user_permissions_jwtuser_id_b57923f0
    on public._user_user_permissions (jwtuser_id);

create index _user_user_permissions_permission_id_fc324062
    on public._user_user_permissions (permission_id);

create table public.imputation_algorithm
(
    id          integer generated by default as identity
        primary key,
    name        varchar(50)  not null,
    description varchar(250) not null
);

alter table public.imputation_algorithm
    owner to sample;

create table public.preprocessor_type
(
    id                integer generated by default as identity
        primary key,
    name              varchar(50)  not null
        unique,
    description       varchar(255) not null,
    schema_enum_value varchar(50)  not null,
    schema            jsonb        not null
);

alter table public.preprocessor_type
    owner to sample;

create index preprocessor_type_name_9ee78278_like
    on public.preprocessor_type (name varchar_pattern_ops);

create table public.train_data_file
(
    id         integer generated by default as identity
        primary key,
    name       varchar(50)              not null,
    created_at timestamp with time zone not null,
    user_id    bigint                   not null,
    constraint train_data_file_name_user_id_2cd12e9d_uniq
        unique (name, user_id)
);

alter table public.train_data_file
    owner to sample;

create index train_data_file_user_id_4b1b9c7d
    on public.train_data_file (user_id);

create table public.survey
(
    id      bigint generated by default as identity
        primary key,
    result  jsonb  not null,
    user_id bigint not null
        unique
);

alter table public.survey
    owner to sample;

create table public.preprocessor
(
    id              integer generated by default as identity
        primary key,
    specific_config jsonb   not null,
    type_id         integer not null
        constraint preprocessor_type_id_03baa324_fk_preprocessor_type_id
            references public.preprocessor_type
            deferrable initially deferred
);

alter table public.preprocessor
    owner to sample;

create index preprocessor_type_id_03baa324
    on public.preprocessor (type_id);

create table public.django_admin_log
(
    id              integer generated by default as identity
        primary key,
    action_time     timestamp with time zone not null,
    object_id       text,
    object_repr     varchar(200)             not null,
    action_flag     smallint                 not null
        constraint django_admin_log_action_flag_check
            check (action_flag >= 0),
    change_message  text                     not null,
    content_type_id integer
        constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co
            references public.django_content_type
            deferrable initially deferred,
    user_id         bigint                   not null
);

alter table public.django_admin_log
    owner to sample;

create index django_admin_log_content_type_id_c4bce8eb
    on public.django_admin_log (content_type_id);

create index django_admin_log_user_id_c564eba6
    on public.django_admin_log (user_id);

create table public.ml_configuration_train_data
(
    id                 bigint generated by default as identity
        primary key,
    mlconfiguration_id integer not null,
    traindata_id       integer not null,
    constraint ml_configuration_train_d_mlconfiguration_id_train_5af4e05b_uniq
        unique (mlconfiguration_id, traindata_id)
);

alter table public.ml_configuration_train_data
    owner to sample;

create index ml_configuration_train_data_mlconfiguration_id_7faa0ee6
    on public.ml_configuration_train_data (mlconfiguration_id);

create index ml_configuration_train_data_traindata_id_ae4be6f3
    on public.ml_configuration_train_data (traindata_id);

create table public.django_session
(
    session_key  varchar(40)              not null
        primary key,
    session_data text                     not null,
    expire_date  timestamp with time zone not null
);

alter table public.django_session
    owner to sample;

create index django_session_session_key_c0390e0f_like
    on public.django_session (session_key varchar_pattern_ops);

create index django_session_expire_date_a5c62663
    on public.django_session (expire_date);

create table public.token_blacklist_outstandingtoken
(
    id         bigint generated by default as identity
        primary key,
    token      text                     not null,
    created_at timestamp with time zone,
    expires_at timestamp with time zone not null,
    user_id    bigint,
    jti        varchar(255)             not null
        constraint token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq
            unique
);

alter table public.token_blacklist_outstandingtoken
    owner to sample;

create table public.token_blacklist_blacklistedtoken
(
    id             bigint generated by default as identity
        primary key,
    blacklisted_at timestamp with time zone not null,
    token_id       bigint                   not null
        unique
        constraint token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk
            references public.token_blacklist_outstandingtoken
            deferrable initially deferred
);

alter table public.token_blacklist_blacklistedtoken
    owner to sample;

create index token_blacklist_outstandingtoken_user_id_83bc629a
    on public.token_blacklist_outstandingtoken (user_id);

create index token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like
    on public.token_blacklist_outstandingtoken (jti varchar_pattern_ops);

create table public.tsd_training_information
(
    id                   integer generated by default as identity
        primary key,
    added_to             timestamp with time zone not null,
    accuracy             double precision         not null,
    levels               integer                  not null,
    tsd_configuration_id integer                  not null
);

alter table public.tsd_training_information
    owner to sample;

create index tsd_training_information_tsd_configuration_id_6863abe8
    on public.tsd_training_information (tsd_configuration_id);

create table public._user
(
    id            serial
        primary key,
    is_active     boolean,
    is_staff      boolean,
    is_superuser  boolean not null,
    last_login    timestamp(6) with time zone,
    email         varchar(255)
        unique,
    first_name    varchar(255),
    language_code varchar(255),
    last_name     varchar(255),
    password      varchar(255),
    role          varchar(255)
        constraint _user_role_check
            check ((role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[]))
);

alter table public._user
    owner to sample;

create table public.train_data
(
    user_id           integer     not null
        constraint fkmkbmx389vokc9mjaly925w6xf
            references public._user,
    created_at        timestamp(6) with time zone,
    id                bigserial
        primary key,
    name              varchar(50) not null,
    time_series_value jsonb       not null
);

alter table public.train_data
    owner to sample;

create table public.json_schemas
(
    schema_type smallint
        constraint json_schemas_schema_type_check
            check ((schema_type >= 0) AND (schema_type <= 5)),
    id          bigint not null
        primary key,
    schema      jsonb,
    ui_schema   jsonb
);

alter table public.json_schemas
    owner to sample;

create table public.data_type
(
    data_type       smallint
        constraint data_type_data_type_check
            check ((data_type >= 0) AND (data_type <= 6)),
    preview_showing boolean,
    schema_id       bigint
        constraint fk5wbsreubr1nicg9balslhwa85
            references public.json_schemas,
    data_type_name  varchar(255) not null
        primary key,
    description     varchar(255)
);

alter table public.data_type
    owner to sample;

create table public.log_messages
(
    log_id        bigint not null
        primary key,
    time_stamp    timestamp(6) with time zone,
    track_id      bigint not null,
    data_set_name varchar(255),
    message       varchar(255),
    send_session  varchar(255)
);

alter table public.log_messages
    owner to sample;

create table public.ml_model
(
    forcasting  boolean,
    created_at  timestamp(6) with time zone,
    id          bigserial
        primary key,
    description varchar(255) not null,
    name        varchar(255) not null,
    "i18n_key"    varchar(255),
    "pyName"      varchar(255)
);

alter table public.ml_model
    owner to sample;

create table public.ml_configuration
(
    user_id     integer     not null
        constraint fkstnjlunvaupix4wjn5uyyfw9a
            references public._user,
    created_at  timestamp(6) with time zone,
    id          bigserial
        primary key,
    ml_model_id bigint      not null
        constraint fkiclwbslemgx092562107wcfhn
            references public.ml_model,
    name        varchar(50) not null,
    description varchar(500)
);

alter table public.ml_configuration
    owner to sample;

create table public.ml_config_data
(
    generation_option   smallint not null
        constraint ml_config_data_generation_option_check
            check ((generation_option >= 0) AND (generation_option <= 1)),
    prediction_length   integer,
    starting_point      integer,
    id                  bigint   not null
        primary key,
    ml_configuration_id bigint
        constraint fkl3mvjgv6wcx1w9yrinigsnly2
            references public.ml_configuration
);

alter table public.ml_config_data
    owner to sample;

create table public.ml_solution
(
    id                  bigserial
        primary key,
    ml_configuration_id bigint
        unique
        constraint fk7aknup9brbrfidi1cyvsb943h
            references public.ml_configuration
);

alter table public.ml_solution
    owner to sample;

create table public.ml_training_information
(
    accuracy          real,
    iterations        integer,
    max_length        integer,
    prediction_length integer,
    reduction_factor  integer,
    target_accuracy   integer,
    target_iterations integer,
    training_time     integer,
    added_to          timestamp(6) with time zone,
    id                bigserial
        primary key,
    ml_solution_id    bigint not null
        constraint fk708w9i5n1gxjmwx8v8axb531n
            references public.ml_solution
);

alter table public.ml_training_information
    owner to sample;

create table public.projects
(
    user_id integer
        constraint fkgc1x3kkp29h3y4rqhnyx00g2l
            references public._user,
    id      bigint not null
        primary key,
    name    varchar(255)
);

alter table public.projects
    owner to sample;

create table public.refresh_token
(
    id          serial
        primary key,
    user_id     integer
        unique
        constraint fkbws85up72jgwebb6ttkjiytg3
            references public._user,
    expiry_date timestamp(6) with time zone,
    token       varchar(255)
);

alter table public.refresh_token
    owner to sample;

create table public.schema_validation_forms
(
    id        bigint not null
        primary key,
    name      varchar(255),
    schema    jsonb,
    ui_schema jsonb
);

alter table public.schema_validation_forms
    owner to sample;

create table public.tracks
(
    repeating boolean,
    id        bigint not null
        primary key,
    name      varchar(255),
    unit      varchar(255)
);

alter table public.tracks
    owner to sample;

create table public.projects_tracks
(
    project_id bigint not null
        constraint fksxj92wca9epx692i8l14uo1pq
            references public.projects,
    tracks_id  bigint not null
        unique
        constraint fkip4su624ox0tq6pq3noc6th29
            references public.tracks,
    primary key (project_id, tracks_id)
);

alter table public.projects_tracks
    owner to sample;

create table public.tracks_allowed_data_types
(
    track_id                          bigint       not null
        constraint fkfkp89ti7s8ux0paxbmxksafsk
            references public.tracks,
    allowed_data_types_data_type_name varchar(255) not null
        constraint fkicbfnxqnxb753in4fxihkk4fw
            references public.data_type,
    primary key (track_id, allowed_data_types_data_type_name)
);

alter table public.tracks_allowed_data_types
    owner to sample;

create table public.tsd_models
(
    created_at      timestamp(6) with time zone,
    id              bigserial
        primary     key,
    description     varchar(255) not null,
    name            varchar(255) not null,
    "i18n_key"      varchar(255),
    "pyName"        varchar(255),
    "display_type"  varchar(255)
);

alter table public.tsd_models
    owner to sample;

create table public.tsd_configuration
(
    user_id      integer     not null
        constraint fkk8kdytj67u0b3tn7wabtiwamk
            references public._user,
    created_at   timestamp(6) with time zone,
    id           bigserial
        primary key,
    tsd_model_id bigint      not null
        constraint fkp6kwr3odp47cx6eofcdipkvha
            references public.tsd_models,
    name         varchar(50) not null,
    description  varchar(500)
);

alter table public.tsd_configuration
    owner to sample;

create table public.tsd_configuration_train_data
(
    id                   bigserial
        primary key,
    train_data_id        bigint not null
        constraint fk13mfquxvh4ua6ba0wspk0ew0m
            references public.train_data,
    tsd_configuration_id bigint
        constraint fkij7a2s4un5vq4qunx6hrcv7te
            references public.tsd_configuration,
    level_config         jsonb
);

alter table public.tsd_configuration_train_data
    owner to sample;

create table public.tsd_options
(
    id       bigserial
        primary key,
    residual varchar(255),
    season   varchar(255),
    trend    varchar(255)
);

alter table public.tsd_options
    owner to sample;

create table public.tsdconfig_data
(
    id         bigserial
        primary key,
    tsd_config bigint not null
        constraint fka8w5d3gjp1977281ktdl7l77x
            references public.tsd_configuration
);

alter table public.tsdconfig_data
    owner to sample;

create table public.plain_data
(
    data_type          smallint
        constraint plain_data_data_type_check
            check ((data_type >= 0) AND (data_type <= 6)),
    frequency          real,
    num_samples        integer,
    position           integer,
    sleep_time         integer,
    id                 bigint      not null
        primary key,
    ml_config_id       bigint
        unique
        constraint fkjatdxcf4lmxup4cxd4v2av6js
            references public.ml_config_data,
    train_data_id      bigint
        constraint fkj5ysbuf61xy09hhwejoqqycuc
            references public.train_data,
    tsd_config_id      bigint
        unique
        constraint fkh8743fn33x7hnefo1pil3257b
            references public.tsdconfig_data,
    tsd_option_id      bigint
        unique
        constraint fkocuvikk3u0538j8w97qnvtw8s
            references public.tsd_options,
    dtype              varchar(31) not null,
    calculation_method varchar(255)
        constraint plain_data_calculation_method_check
            check ((calculation_method)::text = ANY
                   ((ARRAY ['ADDITIVE'::character varying, 'MULTIPLICATIVE'::character varying])::text[])),
    name               varchar(255)
);

alter table public.plain_data
    owner to sample;

create table public.alphabet
(
    character   varchar(1) not null,
    data_set_id bigint     not null
        constraint fki2ri2u5c72hihuxgpdfwfqtup
            references public.plain_data
);

alter table public.alphabet
    owner to sample;

create table public.data_set_custom_values
(
    custom_value  double precision,
    sample_number integer not null,
    data_set_id   bigint  not null
        constraint fk7x3byiamwvb3xb5n84pbalfu1
            references public.plain_data,
    primary key (sample_number, data_set_id)
);

alter table public.data_set_custom_values
    owner to sample;

create table public.tracks_data_sets
(
    data_sets_id bigint not null
        unique
        constraint fkr7hio6tckformeydohj7xhsoi
            references public.plain_data,
    track_id     bigint not null
        constraint fkk7uvwc9r9oiwirve9ymkqc2sm
            references public.tracks,
    primary key (data_sets_id, track_id)
);

alter table public.tracks_data_sets
    owner to sample;

create table public.tsd_level_train_data
(
    id            bigserial
        primary key,
    train_data_id bigint
        constraint fkdfat8ri46e5yn7bywl3t1prwg
            references public.train_data,
    level_config  jsonb
);

alter table public.tsd_level_train_data
    owner to sample;

create table public.tsdconfig_data_train_data
(
    train_data_id     bigint not null
        unique
        constraint fkgdmcn0yvgev431uutsfar7u05
            references public.tsd_level_train_data,
    tsdconfig_data_id bigint not null
        constraint fki69m6g90k6setb7p7vvelig9m
            references public.tsdconfig_data
);

alter table public.tsdconfig_data_train_data
    owner to sample;

