log:
  level: TRACE

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  kafka:
    address: ":9092"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    network: sus-network
    defaultRule: "Host(`{{ .Name }}.docker.localhost`)"
