global:
  scrape_interval:     2s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.


scrape_configs:
  - job_name: 'spring boot scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['springapp-alias:8080']
  - job_name: 'django'
    metrics_path: '/metrics/extended'
    scrape_interval: 2s
    static_configs:
    - targets: ['django-alias:8000']