# Generated by Django 4.2.4 on 2024-02-04 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tsaAPI.model_generation.model_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSDConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name representation for the frontend', max_length=255)),
                ('description', models.CharField(help_text='description of the model for the frontend', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('min_length', models.IntegerField(help_text='reduction value to which every dataset is trimmed before training', null=True)),
                ('imputation_algorithm', models.ForeignKey(help_text='algorithm used to impute data', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.imputationalgorithm')),
                ('processing', models.OneToOneField(help_text='preprocessing to speed up training', null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.preprocessor')),
            ],
            options={
                'db_table': 'tsd_configuration',
            },
        ),
        migrations.CreateModel(
            name='TSDModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name representation for the frontend', max_length=50)),
                ('i18n_key', models.CharField(help_text='translation key for the description', max_length=30)),
                ('description', models.CharField(help_text='description of the model for the frontend', max_length=255)),
                ('pyName', models.CharField(help_text='name of the python file that represents the model', max_length=50)),
                ('display_type', models.CharField(choices=[('SPLITTING', 'split'), ('ONE_DISPLAY', 'one_display'), ('UNDEFINED', 'undefined')], default=tsaAPI.model_generation.model_types.ModelTypes['SPLITTING'], help_text='different display types for the model', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created at')),
            ],
            options={
                'db_table': 'tsd_models',
            },
        ),
        migrations.CreateModel(
            name='TSDTrainingInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_to', models.DateTimeField(auto_now_add=True, help_text='time it was added')),
                ('accuracy', models.FloatField(help_text='accuracy achieved')),
                ('levels', models.IntegerField(help_text='levels of separation')),
                ('tsd_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsaAPI.tsdconfiguration')),
            ],
            options={
                'db_table': 'tsd_training_information',
            },
        ),
        migrations.CreateModel(
            name='TSDConfigurationTrainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_config', models.JSONField(help_text='configuration for level', null=True)),
                ('train_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.traindata')),
                ('tsd_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsaAPI.tsdconfiguration')),
            ],
            options={
                'db_table': 'tsd_configuration_train_data',
            },
        ),
        migrations.AddField(
            model_name='tsdconfiguration',
            name='train_data',
            field=models.ManyToManyField(help_text='n:m, training data for the model', through='tsaAPI.TSDConfigurationTrainData', to='shared.traindata'),
        ),
        migrations.AddField(
            model_name='tsdconfiguration',
            name='tsd_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsaAPI.tsdmodel'),
        ),
        migrations.AddField(
            model_name='tsdconfiguration',
            name='user',
            field=models.ForeignKey(help_text='User who owns this solution builder', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
