log:
  level: DEBUG

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    swarmMode: true
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: sus-network

http:
  middlewares:
    django-stripprefix:
      stripPrefix:
        prefixes:
          - "/django"
    springapp-stripprefix:
      stripPrefix:
        prefixes:
          - "/springboot"
